[build]
command = """
www/build_web.ts &&\
cp www/{style.css,cover.css,color-customizer.js} out/www &&\
cp -r images out/www/images &&\
cp -r fonts out/www/fonts &&\
npx --yes subfont -ir out/www --no-fallbacks
"""
publish = "out/www"
