convert -units PixelsPerInch -density 300 ./figure_2-1_hello_world.png ./figure_2-1_hello_world.png
convert -units PixelsPerInch -density 300 ./figure_2-2_table_etc.png ./figure_2-2_table_etc.png
convert -units PixelsPerInch -density 300 ./screenshot_validation_error.png ./screenshot_validation_error.png
convert -units PixelsPerInch -density 300 ./screenshot_click_to_load.png ./screenshot_click_to_load.png
convert -units PixelsPerInch -density 300 ./screenshot_total_contacts.png ./screenshot_total_contacts.png
convert -units PixelsPerInch -density 300 ./screenshot_stacked_actions.png ./screenshot_stacked_actions.png
convert -units PixelsPerInch -density 300 ./screenshot_checkboxes.png ./screenshot_checkboxes.png
convert -units PixelsPerInch -density 300 ./screenshot_progress_bar.png ./screenshot_progress_bar.png
convert -units PixelsPerInch -density 300 ./screenshot_sweet_alert.png ./screenshot_sweet_alert.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_list.png ./screenshot_hyperview_list.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_search.png ./screenshot_hyperview_search.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_refresh_cropped.png ./screenshot_hyperview_refresh_cropped.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_detail_cropped.png ./screenshot_hyperview_detail_cropped.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_edit.png ./screenshot_hyperview_edit.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_delete_cropped.png ./screenshot_hyperview_delete_cropped.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_add.png ./screenshot_hyperview_add.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_toast.png ./screenshot_hyperview_toast.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_swipe.png ./screenshot_hyperview_swipe.png
convert -units PixelsPerInch -density 300 ./screenshot_hyperview_swipe_delete.png ./screenshot_hyperview_swipe_delete.png
